global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   width: 15.0
   height: 15.0
   resolution: 0.05
   static_map: true
   rolling_window: false
   update_frequency: 5.0
   publish_frequency: 2.0

